apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - mongodb/mongo.yaml

configMapGenerator:
  - name: backend-config
    literals:
      - GITHUB_API_URL=https://api.github.com
      - AUTH_MODE=dev
      - DEV_USER=devuser
      - ADMIN_USERS=devuser
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: agent-knowledge-hub-secrets
    files:
      - etc/.secrets/MONGO_URI
    options:
      disableNameSuffixHash: true
  - name: mongodb-secrets
    files:
      - etc/.secrets/MONGODB_BACKUP_USER
      - etc/.secrets/MONGODB_BACKUP_PASSWORD
      - etc/.secrets/MONGODB_CLUSTER_ADMIN_USER
      - etc/.secrets/MONGODB_CLUSTER_ADMIN_PASSWORD
      - etc/.secrets/MONGODB_CLUSTER_MONITOR_USER
      - etc/.secrets/MONGODB_CLUSTER_MONITOR_PASSWORD
      - etc/.secrets/MONGODB_USER_ADMIN_USER
      - etc/.secrets/MONGODB_USER_ADMIN_PASSWORD
    options:
      disableNameSuffixHash: true
