apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: agent-knowledge-hub-backend
    newName: slaclab/agent-knowledge-hub-backend
    newTag: dev
  - name: agent-knowledge-hub-frontend
    newName: slaclab/agent-knowledge-hub-frontend
    newTag: dev

configMapGenerator:
  - name: backend-config
    literals:
      - MONGO_URI=mongodb://mongodb-rs0.dev.svc.cluster.local/agent-skills?replicaSet=rs0
      - GITHUB_API_URL=https://api.github.com
      - AUTH_MODE=dev
      - DEV_USER=devuser
      - ADMIN_USERS=devuser
    options:
      disableNameSuffixHash: true
