apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - mongo.yaml

secretGenerator:
  - name: mongodb-secrets
    files:
      - etc/.secrets/MONGODB_BACKUP_USER
      - etc/.secrets/MONGODB_BACKUP_PASSWORD
      - etc/.secrets/MONGODB_CLUSTER_ADMIN_USER
      - etc/.secrets/MONGODB_CLUSTER_ADMIN_PASSWORD
      - etc/.secrets/MONGODB_CLUSTER_MONITOR_USER
      - etc/.secrets/MONGODB_CLUSTER_MONITOR_PASSWORD
      - etc/.secrets/MONGODB_USER_ADMIN_USER
      - etc/.secrets/MONGODB_USER_ADMIN_PASSWORD
    options:
      disableNameSuffixHash: true
