apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-knowledge-hub-stage

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

configMapGenerator:
  - name: backend-config
    literals:
      - GITHUB_API_URL=https://api.github.com
      - AUTH_MODE=vouchproxy
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: agent-knowledge-hub-secrets
    files:
      - etc/.secrets/MONGO_URI
      - etc/.secrets/GITHUB_TOKEN
      - etc/.secrets/ADMIN_USERS
    options:
      disableNameSuffixHash: true
