apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-knowledge-hub-stage

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress-frontend.yaml
  - ingress-api.yaml
  - ingress-marketplace-redirect.yaml
  - network-policy-backend.yaml

configMapGenerator:
  - name: backend-config
    literals:
      - GITHUB_API_URL=https://api.github.com
      - AUTH_MODE=vouchproxy
      - JWT_JWKS_URI=https://dex.slac.stanford.edu/keys
      - JWT_ISSUER=https://dex.slac.stanford.edu
      - JWT_AUDIENCE=s3df
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: agent-knowledge-hub-secrets
    files:
      - etc/.secrets/MONGO_URI
      - etc/.secrets/GITHUB_TOKEN
      - etc/.secrets/ADMIN_USERS
      - etc/.secrets/INTERNAL_API_SECRET
    options:
      disableNameSuffixHash: true
